version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: '/'
    schedule:
      interval: weekly
    groups:
      nuget:
        patterns:
          - "NuGet*"
      xunit:
        patterns:
          - "xunit*"
      gitversioning:
        patterns:
          - "Nerdbank.GitVersioning"
          - "nbgv"

  - package-ecosystem: dotnet-sdk
    directory: '/'
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: /NuNuGet
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /Tests/NuNuGet.Reference.0.5
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /Tests/NuNuGet.Reference.0.6
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /Tests/NuNuGet.Tests
    schedule:
      interval: daily
